# Generated by Django 4.2.2 on 2023-08-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=333)),
                ('description', models.CharField(max_length=322)),
                ('image', models.ImageField(upload_to='off_img/')),
            ],
        ),
    ]
