# Generated by Django 4.2.2 on 2023-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0002_alter_tech_description_alter_tech_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33)),
                ('email', models.EmailField(max_length=33)),
                ('phone', models.IntegerField(max_length=33)),
                ('Device', models.CharField(max_length=33)),
            ],
        ),
    ]
