# Generated by Django 4.2.2 on 2023-08-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0003_technology'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technology',
            new_name='NewModel',
        ),
    ]
